# 2. Solving Linear Equation
Python의 numpy를 이용하여 linear equation을 풀어보는 실습을 진행합니다.

In [0]:
import numpy as np
import matplotlib.pyplot as plt

다음과 같은 linear equation을 푸는 것을 생각해 봅시다.
 -  2x + 4y - 2z = 2
 -  4x + 9y - 3z = 8
 - -2x - 3y + 7z = 10

matrix A와 vector b를 아래와 같이 정의할 수 있습니다.


In [2]:
A = np.array([[2,4,-2],[4,9,-3],[-2,-3,7]])
b = np.array([[2],[8],[10]])

print(A)
print(A.shape)
print(b)
print(b.shape)

print(A[0,0])
print(A[1,0])

[[ 2  4 -2]
 [ 4  9 -3]
 [-2 -3  7]]
(3, 3)
[[ 2]
 [ 8]
 [10]]
(3, 1)
2
4


augmented matrix [A b]를 생성해 봅시다. 
- np.concatenate를 axis를 정의하여 사용하면 두 matrix를 합칠 수가 있습니다. 
- np.c_, np.r_을 사용할 수도 있습니다. 
- np.c_[]는 column을 이어 붙일 수 있습니다. np.r_[]은 row로 이어붙일 수 있습니다. 

In [3]:
print(np.c_[A,b])
print(np.concatenate((A,b),axis=1))

[[ 2  4 -2  2]
 [ 4  9 -3  8]
 [-2 -3  7 10]]
[[ 2  4 -2  2]
 [ 4  9 -3  8]
 [-2 -3  7 10]]


손으로 풀었던 과정을 파이썬 코드를 이용해 다시 반복해 보겠습니다. 먼저 첫 번째 pivot을 이용하여 2번째, 3번째 row의 첫 번째 값들을 0으로 만듭시다.

In [4]:
Ab = np.concatenate((A,b),axis=1)
print(Ab)
l21 = -Ab[1,0]/Ab[0,0]
Ab[1,:] = l21*Ab[0,:] + Ab[1,:]
print(Ab)
l31 = -Ab[2,0]/Ab[0,0]
Ab[2,:] = l31*Ab[0,:] + Ab[2,:]
print(Ab)

[[ 2  4 -2  2]
 [ 4  9 -3  8]
 [-2 -3  7 10]]
[[ 2  4 -2  2]
 [ 0  1  1  4]
 [-2 -3  7 10]]
[[ 2  4 -2  2]
 [ 0  1  1  4]
 [ 0  1  5 12]]


다음은 두 번째 pivot을 이용하여 세 번째 row의 두 번째 값도 0으로 만듭시다. 그러면 upper triangular matrix U가 완성될 것입니다.

In [5]:
l32 = -Ab[2,1]/Ab[1,1]
Ab[2,:] = l32*Ab[1,:] + Ab[2,:]
print(Ab)

[[ 2  4 -2  2]
 [ 0  1  1  4]
 [ 0  0  4  8]]


우리의 linear equation은 다음과 같이 정리가 되었습니다.
- -2x + 4y - 2z  = 2
-        y +  z  = 4
-            4z  = 8

우리는 back substitution을 통해 z, y, x를 순서대로 구할 수 있습니다.

In [6]:
z = Ab[2,3]/Ab[2,2]
print('z =',z)
y = (Ab[1,3]-Ab[1,2]*z)/Ab[1,1]
print('y =',y)
x = (Ab[0,3]-Ab[0,2]*z-Ab[0,1]*y)/Ab[0,0]
print('x =',x)

z = 2.0
y = 2.0
x = -1.0


In [7]:
r = np.matmul(A,[[x],[y],[z]])
print('r=',r)
print('b=',b)

r= [[ 2.]
 [ 8.]
 [10.]]
b= [[ 2]
 [ 8]
 [10]]


이번에는 같은 문제를 matrix를 이용하여 풀어 보겠습니다. Elimination matrix를 간편하게 정의하기 위해 Identity matrix를 먼저 정의합니다.

In [8]:
I = np.identity(3)
print(I)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
print('step 0 - [A b]')
Ab = np.concatenate((A,b),axis=1)
print(Ab)

print('E21:')
E21 = np.identity(3)
E21[1,0] = -Ab[1,0]/Ab[0,0]
print(E21)

print('step 1 - E21 [A b]')
Ab = np.matmul(E21,Ab)
print(Ab)

print('E31: ')
E31 = np.identity(3)
E31[2,0] = -Ab[2,0]/Ab[0,0]
print(E31)

print('step 2 - E31 E21 [A b]')
Ab = np.matmul(E31,Ab)
print(Ab)

print('E32:')
E32 = np.identity(3)
E32[2,1] = -Ab[2,1]/Ab[1,1]
print(E32)

print('step 3 - E32 E31 E21 [A b]')
Ab = np.matmul(E32,Ab)
print(Ab)

step 0 - [A b]
[[ 2  4 -2  2]
 [ 4  9 -3  8]
 [-2 -3  7 10]]
E21:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  0.  1.]]
step 1 - E21 [A b]
[[ 2.  4. -2.  2.]
 [ 0.  1.  1.  4.]
 [-2. -3.  7. 10.]]
E31: 
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]
step 2 - E31 E21 [A b]
[[ 2.  4. -2.  2.]
 [ 0.  1.  1.  4.]
 [ 0.  1.  5. 12.]]
E32:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]
step 3 - E32 E31 E21 [A b]
[[ 2.  4. -2.  2.]
 [ 0.  1.  1.  4.]
 [ 0.  0.  4.  8.]]


위의 과정은 python을 이용한 matrix의 연산에 익숙해지기 위한 연습입니다. 사실 numpy에는 linear equation solver 함수를 이미 가지고 있습니다. np.linalg.solve()라는 함수에 A와 b를 넣으면 x를 연산해 줍니다.

In [10]:
xyz = np.linalg.solve(A,b)
print(xyz)

[[-1.]
 [ 2.]
 [ 2.]]


여러 b에 대해 한꺼번에 solution을 구할 수도 있습니다.

In [11]:
np.linalg.solve(A,np.concatenate((b,2*b,3*b),axis=1))

array([[-1., -2., -3.],
       [ 2.,  4.,  6.],
       [ 2.,  4.,  6.]])

다음은 연산시간을 측정하기 위해 time이라는 패키지를 불러오겠습니다.

In [0]:
import time

3x3 matrix A 와 3x1 vector b가 있을 때 Ax=b를 푸는 시간을 측정해 봅시다.

In [13]:
s0 = time.time()
np.linalg.solve(A,b)
print(time.time() -s0,'sec')

0.0002803802490234375 sec
